# Site settings
title: "Reverie..."
author: "Shilpa Amberker"
description: "The word Raverie's literal translates is 'floating in one's thought'. Through this blog I wish to share my Thoughts, Ideas and Views and mainly those i have learnt in the process my search for knowledge. This blog is broadly divide into a few sections but it is hard to classify my varied interests into these sections and hence there is a 'Misc' section where i can talk about a whole lot of things!"
keywords: "Software Engineering, Mathematics, Programming, Machine-Learning, Analytics, Sketching, Painting, Photography, Books, Philosophy"
biography: "I am a Software Developer and an enthusiastic learner. You can find more about me @ <a href='http://kriyavikalpa.com/'>"
colophon: "©2018 Shilpa Amberker. This site is hosted at <a href='https://shilpavijay.github.io/'>Github Pages</a> and created with <3 by <a href='http://jekyllrb.com/'>Jekyll</a>."

baseurl: ""
url: "http://kriyavikalpa.com/"

twitter_username: shilpaab
github_username: shilpavijay
linkedin_username: shilpaamberker
facebook_username: shilpa.amberker
google-analytics: UA-69060-5

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
